from construct import *

protocol_discriminator = Enum(
    Nibble,
    GROUP_CALL_CONTROL=0,
    BROADCAST_CALL_CONTROL=1,
    PDSS1=2,
    CALL_CONTROL=3,
    PDSS2=4,
    MOBILITY_MANAGEMENT=5,
    RADIO_RESOURCES=6,
    SMS=9,
    NON_CALL_RELATED_SS=0xb,
    EXTENSION_OF_PD=0xe,
    TEST_PROCEDURES=0xf
)

message_type = Enum(Byte, CP_DATA=1, CP_ACK=4, CP_ERROR=0x10)

cp_cause = Enum(
    Byte,
    NETWORK_FAILURE=17, CONGESTION=22, INVALID_TID=81, SEMANTICALLY_INCORRECT=95, INVALID_MANDATORY_INFORMATION=96,
    MESSAGE_TYPE_NOT_IMPLEMENTED=97, NOT_COMPATIBLE_WITH_PROTOCOL_STATE=98, INFORMATION_ELEMENT_NOT_IMPLEMENTED=99,
    PROTOCOL_ERROR=111
)

rp_mti = Enum(
    BitsInteger(3),
    RP_DATA_MS_TO_N=0, RP_DATA_N_TO_MS=1, RP_ACK_MS_TO_N=2, RP_ACK_N_TO_MS=3, RP_ERROR_MS_TO_N=4, RP_ERROR_N_TO_MS=5,
    RP_SMMA=6
)

rp_cause_value = Enum(
    BitsInteger(7),
    UNASSIGNED_NUMBER=1, OPERATOR_DETERMINED_BARRING=8, CALL_BARRED=10, RESERVED=11, SHORT_MESSAGE_TRANSFER_REJECTED=21,
    MEMORY_CAPACITY_EXCEEDED=22, DESTINATION_OUT_OF_ORDER=27, UNIDENTIFIED_SUBSCRIBER=28, FACILITY_REJECTED=29,
    UNKNOWN_SUBSCRIBER=30, NETWORK_OUT_OF_ORDER=38, TEMPORARY_FAILIURE=41, CONJESTION=42, RESOURCES_UNAVAILABLE=47,
    REQUESTED_FACILITY_NOT_SUBSCRIBED=50, REQUESTED_FACILITY_NOT_IMPLEMENTED=69,
    INVALID_SHORT_MESSAGE_TRANSFER_REFERENCE=81, SMANTICALLY_INCORRECT_MESSAGE=95, INVALID_MANDATORY_INFORMATION=96,
    MESSAGE_TYPE_NON_EXISTENT=97, MESSAGE_NOT_COMPATIBLE_WITH_STATE=98, INFORMATION_ELEMENT_NON_EXISTENT=99,
    PROTOCOL_ERROR=111, INTERWORKING=127
)
