from construct import *

protocol_discriminator = Enum(
    Nibble,
    GROUP_CALL_CONTROL=0,
    BROADCAST_CALL_CONTROL=1,
    PDSS1=2,
    CALL_CONTROL=3,
    PDSS2=4,
    MOBILITY_MANAGEMENT=5,
    RADIO_RESOURCES=6,
    SMS=9,
    NON_CALL_RELATED_SS=0xb,
    EXTENSION_OF_PD=0xe,
    TEST_PROCEDURES=0xf
)

message_type = Enum(Byte, CP_DATA=1, CP_ACK=4, CP_ERROR=0x10)

cp_cause = Enum(
    Byte,
    NETWORK_FAILURE=17, CONGESTION=22, INVALID_TID=81, SEMANTICALLY_INCORRECT=95, INVALID_MANDATORY_INFORMATION=96,
    MESSAGE_TYPE_NOT_IMPLEMENTED=97, NOT_COMPATIBLE_WITH_PROTOCOL_STATE=98, INFORMATION_ELEMENT_NOT_IMPLEMENTED=99,
    PROTOCOL_ERROR=111
)
